package dns

import (
	"github.com/prometheus/client_golang/prometheus"
)

import (
	"github.com/prometheus/blackbox_exporter/internal/metrics/other"
)

// Duration of DNS request by phase
type ProbeDurationSeconds struct {
	*prometheus.GaugeVec
	extra ProbeDurationSecondsExtra
}

func NewProbeDurationSeconds() ProbeDurationSeconds {
	labels := []string{other.AttrPhase("").Key()}
	return ProbeDurationSeconds{GaugeVec: prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Name: "probe_dns_duration_seconds",
		Help: "Duration of DNS request by phase",
	}, labels)}
}

func (m ProbeDurationSeconds) With(phase other.AttrPhase, extras ...interface{}) prometheus.Gauge {
	return m.GaugeVec.WithLabelValues(string(phase))
}

// Deprecated: Use [ProbeDurationSeconds.With] instead
func (m ProbeDurationSeconds) WithLabelValues(lvs ...string) prometheus.Gauge {
	return m.GaugeVec.WithLabelValues(lvs...)
}

type ProbeDurationSecondsExtra struct {
}

/*
State {
    name: "vec.go.j2",
    current_block: None,
    auto_escape: None,
    ctx: {
        "AttrExtra": "ProbeDurationSecondsExtra",
        "Instr": "Gauge",
        "InstrMap": {
            "counter": "Counter",
            "gauge": "Gauge",
            "histogram": "Histogram",
            "updowncounter": "Gauge",
        },
        "Name": "probe.duration.seconds",
        "Type": "ProbeDurationSeconds",
        "attributes": [
            {
                "brief": "Probe phase",
                "name": "phase",
                "requirement_level": "required",
                "stability": "stable",
                "type": {
                    "members": [
                        {
                            "brief": none,
                            "deprecated": none,
                            "id": "resolve",
                            "note": none,
                            "stability": "stable",
                            "value": "resolve",
                        },
                        {
                            "brief": none,
                            "deprecated": none,
                            "id": "connect",
                            "note": none,
                            "stability": "stable",
                            "value": "connect",
                        },
                        {
                            "brief": none,
                            "deprecated": none,
                            "id": "request",
                            "note": none,
                            "stability": "stable",
                            "value": "request",
                        },
                        {
                            "brief": none,
                            "deprecated": none,
                            "id": "tls",
                            "note": none,
                            "stability": "stable",
                            "value": "tls",
                        },
                        {
                            "brief": none,
                            "deprecated": none,
                            "id": "processing",
                            "note": none,
                            "stability": "stable",
                            "value": "processing",
                        },
                        {
                            "brief": none,
                            "deprecated": none,
                            "id": "transfer",
                            "note": none,
                            "stability": "stable",
                            "value": "transfer",
                        },
                        {
                            "brief": none,
                            "deprecated": none,
                            "id": "setup",
                            "note": none,
                            "stability": "stable",
                            "value": "setup",
                        },
                        {
                            "brief": none,
                            "deprecated": none,
                            "id": "rtt",
                            "note": none,
                            "stability": "stable",
                            "value": "rtt",
                        },
                        {
                            "brief": none,
                            "deprecated": none,
                            "id": "check",
                            "note": none,
                            "stability": "stable",
                            "value": "check",
                        },
                    ],
                },
            },
        ],
        "ctx": {
            "attributes": [
                {
                    "brief": "Probe phase",
                    "name": "phase",
                    "requirement_level": "required",
                    "stability": "stable",
                    "type": {
                        "members": [
                            {
                                "brief": none,
                                "deprecated": none,
                                "id": "resolve",
                                "note": none,
                                "stability": "stable",
                                "value": "resolve",
                            },
                            {
                                "brief": none,
                                "deprecated": none,
                                "id": "connect",
                                "note": none,
                                "stability": "stable",
                                "value": "connect",
                            },
                            {
                                "brief": none,
                                "deprecated": none,
                                "id": "request",
                                "note": none,
                                "stability": "stable",
                                "value": "request",
                            },
                            {
                                "brief": none,
                                "deprecated": none,
                                "id": "tls",
                                "note": none,
                                "stability": "stable",
                                "value": "tls",
                            },
                            {
                                "brief": none,
                                "deprecated": none,
                                "id": "processing",
                                "note": none,
                                "stability": "stable",
                                "value": "processing",
                            },
                            {
                                "brief": none,
                                "deprecated": none,
                                "id": "transfer",
                                "note": none,
                                "stability": "stable",
                                "value": "transfer",
                            },
                            {
                                "brief": none,
                                "deprecated": none,
                                "id": "setup",
                                "note": none,
                                "stability": "stable",
                                "value": "setup",
                            },
                            {
                                "brief": none,
                                "deprecated": none,
                                "id": "rtt",
                                "note": none,
                                "stability": "stable",
                                "value": "rtt",
                            },
                            {
                                "brief": none,
                                "deprecated": none,
                                "id": "check",
                                "note": none,
                                "stability": "stable",
                                "value": "check",
                            },
                        ],
                    },
                },
            ],
            "brief": "Duration of DNS request by phase",
            "events": [],
            "id": "metric.dns.probe.duration.seconds",
            "instrument": "gauge",
            "lineage": {
                "attributes": {
                    "phase": {
                        "inherited_fields": [
                            "brief",
                            "note",
                            "stability",
                        ],
                        "locally_overridden_fields": [
                            "requirement_level",
                        ],
                        "source_group": "registry.other",
                    },
                },
                "provenance": {
                    "path": "../../semconv/dns/metrics.yaml",
                    "registry_id": "main",
                },
            },
            "metric_name": "probe_dns_duration_seconds",
            "name": none,
            "root_namespace": "dns",
            "span_kind": none,
            "stability": "stable",
            "type": "metric",
            "unit": "s",
        },
        "for_each_attr": <macro for_each_attr>,
        "module": "github.com/prometheus/blackbox_exporter/internal/metrics",
    },
    env: Environment {
        globals: {
            "concat_if": weaver_forge::extensions::util::concat_if,
            "cycler": minijinja_contrib::globals::cycler,
            "debug": minijinja::functions::builtins::debug,
            "dict": minijinja::functions::builtins::dict,
            "joiner": minijinja_contrib::globals::joiner,
            "namespace": minijinja::functions::builtins::namespace,
            "params": {
                "module": "github.com/prometheus/blackbox_exporter/internal/metrics",
                "params": {
                    "module": "github.com/prometheus/blackbox_exporter/internal/metrics",
                },
            },
            "range": minijinja::functions::builtins::range,
            "template": {},
        },
        tests: [
            "!=",
            "<",
            "<=",
            "==",
            ">",
            ">=",
            "array",
            "boolean",
            "defined",
            "deprecated",
            "divisibleby",
            "endingwith",
            "enum",
            "enum_type",
            "eq",
            "equalto",
            "escaped",
            "even",
            "experimental",
            "false",
            "filter",
            "float",
            "ge",
            "greaterthan",
            "gt",
            "in",
            "int",
            "integer",
            "iterable",
            "le",
            "lessthan",
            "lower",
            "lt",
            "mapping",
            "ne",
            "none",
            "number",
            "odd",
            "safe",
            "sameas",
            "sequence",
            "simple_type",
            "stable",
            "startingwith",
            "string",
            "template_type",
            "test",
            "true",
            "undefined",
            "upper",
        ],
        filters: [
            "abs",
            "acronym",
            "ansi_bg_black",
            "ansi_bg_blue",
            "ansi_bg_bright_black",
            "ansi_bg_bright_blue",
            "ansi_bg_bright_cyan",
            "ansi_bg_bright_green",
            "ansi_bg_bright_magenta",
            "ansi_bg_bright_red",
            "ansi_bg_bright_white",
            "ansi_bg_bright_yellow",
            "ansi_bg_cyan",
            "ansi_bg_green",
            "ansi_bg_magenta",
            "ansi_bg_red",
            "ansi_bg_white",
            "ansi_bg_yellow",
            "ansi_black",
            "ansi_blue",
            "ansi_bold",
            "ansi_bright_black",
            "ansi_bright_blue",
            "ansi_bright_cyan",
            "ansi_bright_green",
            "ansi_bright_magenta",
            "ansi_bright_red",
            "ansi_bright_white",
            "ansi_bright_yellow",
            "ansi_cyan",
            "ansi_green",
            "ansi_italic",
            "ansi_magenta",
            "ansi_red",
            "ansi_strikethrough",
            "ansi_underline",
            "ansi_white",
            "ansi_yellow",
            "attr",
            "attribute_id",
            "attribute_namespace",
            "attribute_registry_file",
            "attribute_registry_namespace",
            "attribute_registry_title",
            "attribute_sort",
            "batch",
            "body_fields",
            "bool",
            "camel_case",
            "camel_case_const",
            "capitalize",
            "capitalize_first",
            "comment",
            "comment_with_prefix",
            "count",
            "d",
            "default",
            "dictsort",
            "e",
            "enum_type",
            "escape",
            "filesizeformat",
            "first",
            "flatten",
            "float",
            "groupby",
            "indent",
            "instantiated_type",
            "int",
            "items",
            "join",
            "kebab_case",
            "kebab_case_const",
            "last",
            "length",
            "lines",
            "list",
            "lower",
            "lower_case",
            "map",
            "map_text",
            "markdown_to_html",
            "max",
            "metric_namespace",
            "min",
            "not_required",
            "pascal_case",
            "pascal_case_const",
            "pluralize",
            "pprint",
            "print_member_value",
            "regex_replace",
            "reject",
            "rejectattr",
            "replace",
            "required",
            "reverse",
            "round",
            "safe",
            "screaming_kebab_case",
            "screaming_snake_case",
            "screaming_snake_case_const",
            "select",
            "selectattr",
            "slice",
            "snake_case",
            "snake_case_const",
            "sort",
            "split",
            "split_id",
            "string",
            "striptags",
            "sum",
            "title",
            "title_case",
            "tojson",
            "toyaml",
            "trim",
            "truncate",
            "type_mapping",
            "unique",
            "upper",
            "upper_case",
            "urlencode",
        ],
        templates: [
            "vec.go.j2",
        ],
    },
}
*/
